---
version: "3"
services:
 devopsdb:
   image: shaikmustafa/harikanew:dbimage
   ports:
     - "3306:3306"

 application:
   image: shaikmustafa/harikanew:appimage
   deploy:
     replicas: 3
   ports:
     - "1111:8080"
   depends_on:
     - "devopsdb"
