---
version: "3"
services:
 devopsdb:
   image: rohitryali9/myrepo:db
   ports:
     - "3306:3306"

 application:
   image: rohitryali9/myrepo:app
   deploy:
     replicas: 3
   ports:
     - "1111:8080"
   depends_on:
     - "devopsdb"
